<template>
  <div class="hub-view">
    <div class="hub-section-header">
      <h1 class="section-title">AI Hub</h1>
      <p class="section-desc">
        Raporty wygenerowane przez AI na podstawie analizy systemu — SQL, ETL, zależności, jakość danych i ryzyko wdrożeń.
        Kliknij kartę, aby zobaczyć szczegóły i podgląd raportu.
      </p>
    </div>

    <FilterBar :categories="filterCategories" :active="activeCategory" @select="activeCategory = $event" />

    <div class="report-grid">
      <ReportCard
        v-for="r in sortedReports"
        :key="r.id"
        :report="r"
        :active="activeReport === r.id"
        @toggle="toggleReport(r.id)"
      />
    </div>
  </div>
</template>

<script setup>
import { ref, computed } from 'vue'
import FilterBar from './FilterBar.vue'
import ReportCard from './ReportCard.vue'

const activeReport = ref(null)
const activeCategory = ref('all')

// ---- Pełna lista raportów (identyczna z oryginałem) ----
const allReports = [
  { id: 'sql-performance-advisor', category: 'sql', title: 'SQL Performance Advisor', desc: 'Analiza zapytań SQL (Oracle/Snowflake) pod kątem wydajności. Wykrywa FULL TABLE SCAN, brak indeksów, CARTESIAN JOIN i proponuje optymalizacje.', icon: '<svg width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><polyline points="22 12 18 12 15 21 9 3 6 12 2 12"/></svg>', accent: '#7c4dff', gradient: 'linear-gradient(135deg, #7c4dff, #536dfe)', tags: ['SQL', 'Performance', 'Oracle', 'Snowflake'], status: 'new', statusLabel: 'NOWY', date: '2026-07-08', author: 'A. Kowalski', version: '2.3.1', url: '/ai-reports/sql-performance-advisor.html', metric: { label: 'Performance Score', value: 92, unit: '/100', display: 92, color: '#7c4dff' }, findings: ['5 zapytań z FULL TABLE SCAN na tabelach >1M rekordów', 'Brak indeksu na JOIN w 3 kluczowych widokach', 'CARTESIAN JOIN wykryty w raportach miesięcznych', 'Niepotrzebny DISTINCT w 2 zapytaniach agregujących'], recommendations: ['Dodaj indeksy kompozytowe na kolumnach JOIN', 'Zastosuj PARTITION BY dla tabel faktów', 'Zamień DISTINCT na EXISTS w podzapytaniach', 'Przepisz CARTESIAN JOIN na INNER JOIN z kluczami'] },
  { id: 'sql-code-review', category: 'sql', title: 'AI Code Review for SQL', desc: 'Automatyczny przegląd kodu SQL jak Senior Developer. Analiza czytelności, standardów, wydajności i potencjalnych błędów.', icon: '<svg width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><polyline points="16 18 22 12 16 6"/><polyline points="8 6 2 12 8 18"/></svg>', accent: '#651fff', gradient: 'linear-gradient(135deg, #651fff, #d500f9)', tags: ['Code Review', 'SQL', 'Best Practices'], status: 'beta', statusLabel: 'BETA', date: '2026-07-07', author: 'M. Nowak', version: '1.0.5', url: '/ai-reports/sql-code-review.html', metric: { label: 'Code Quality', value: 74, unit: '/100', display: 74, color: '#651fff' }, findings: ['Niespójne nazewnictwo (CamelCase vs SNAKE_CASE) w 12 miejscach', 'Brak komentarzy w złożonych CTE', 'Użycie SELECT * w 8 widokach produkcyjnych', 'Brak obsługi NULL w kolumnach numerycznych'], recommendations: ['Ustandaryzuj nazewnictwo na SNAKE_CASE', 'Dodaj komentarze do każdego CTE >10 linii', 'Zamień SELECT * na jawne kolumny', 'Dodaj COALESCE/NVL dla kolumn numerycznych'] },
  { id: 'sql-lineage', category: 'sql', title: 'SQL Lineage Report', desc: 'Analiza zależności między tabelami i widokami w Oracle/Snowflake. Mapowanie przepływu danych od źródła do DWH z wykryciem krytycznych ścieżek.', icon: '<svg width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"/></svg>', accent: '#536dfe', gradient: 'linear-gradient(135deg, #536dfe, #448aff)', tags: ['SQL', 'Lineage', 'Oracle', 'Snowflake'], status: 'stable', statusLabel: 'STABILNY', date: '2026-07-04', author: 'K. Wiśniewska', version: '3.1.0', url: '/ai-reports/sql-lineage.html', metric: { label: 'Pokrycie', value: 95, unit: '%', display: 95, color: '#536dfe' }, findings: ['12 łańcuchów zależności wykrytych', '3 krytyczne ścieżki bez backupu', '2 widoki z cyklicznymi referencjami'], recommendations: ['Dodaj materializację dla krytycznych widoków', 'Przerwij cykle w zależnościach'] },
  { id: 'etl-dependency', category: 'etl', title: 'ETL Dependency Analyzer', desc: 'Analiza eksportu Informatica PowerCenter XML. Generuje pełną mapę zależności z wykryciem nieużywanych mappingów i osieroconych workflow.', icon: '<svg width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><polygon points="12 2 22 8.5 22 15.5 12 22 2 15.5 2 8.5 12 2"/><line x1="12" y1="22" x2="12" y2="15.5"/><polyline points="22 8.5 12 15.5 2 8.5"/></svg>', accent: '#00c853', gradient: 'linear-gradient(135deg, #00c853, #00e676)', tags: ['ETL', 'Informatica', 'Dependency', 'XML'], status: 'new', statusLabel: 'NOWY', date: '2026-07-08', author: 'J. Kamiński', version: '2.0.2', url: '/ai-reports/etl-dependency.html', metric: { label: 'Pokrycie analizy', value: 88, unit: '%', display: 88, color: '#00c853' }, findings: ['Nieużywane: 3 mappingi, 2 sesje, 1 workflow', '5 mappingów o zbyt wysokiej złożoności (>50 transformacji)', '7 duplikujących się transformacji Expression', '2 osierocone workflow bez sesji'], recommendations: ['Usuń nieużywane obiekty (redukcja kosztów utrzymania)', 'Podziel złożone mappingi na warstwy', 'Wydziel powielone Expression do osobnych obiektów'] },
  { id: 'etl-complexity', category: 'etl', title: 'ETL Complexity Report', desc: 'Wylicza stopień skomplikowania procesów ETL na podstawie transformacji, lookupów, joinów i zagnieżdżonych mappingów z wykresem radarowym.', icon: '<svg width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M18 20V10"/><path d="M12 20V4"/><path d="M6 20v-6"/></svg>', accent: '#00e676', gradient: 'linear-gradient(135deg, #00e676, #69f0ae)', tags: ['ETL', 'Complexity', 'Analytics'], status: 'new', statusLabel: 'NOWY', date: '2026-07-08', author: 'P. Lewandowski', version: '1.0.3', url: '/ai-reports/etl-complexity.html', metric: { label: 'Complexity Score', value: 72, unit: '/100', display: 72, color: '#ffab00' }, findings: ['Średnia liczba transformacji na mapping: 34', '8 mappingów z kategorii "krytyczny"', 'Najwyższy wynik: 94/100 (mapping FCT_SALES_LOAD)', 'Wąskie gardła w warstwie BUFF'], recommendations: ['Refaktoryzuj mappingi z score >80', 'Wprowadź standardowe szablony ETL', 'Dodaj warstwę stagingową dla lookupów'] },
  { id: 'data-flow', category: 'etl', title: 'Data Flow Visualizer', desc: 'Interaktywny graf przepływu danych od źródła przez Landing, BUFF, DM do raportu.', icon: '<svg width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><line x1="12" y1="2" x2="12" y2="6"/><line x1="12" y1="18" x2="12" y2="22"/><line x1="4.93" y1="4.93" x2="7.76" y2="7.76"/><line x1="16.24" y1="16.24" x2="19.07" y2="19.07"/><line x1="2" y1="12" x2="6" y2="12"/><line x1="18" y1="12" x2="22" y2="12"/><line x1="4.93" y1="19.07" x2="7.76" y2="16.24"/><line x1="16.24" y1="7.76" x2="19.07" y2="4.93"/></svg>', accent: '#00bcd4', gradient: 'linear-gradient(135deg, #00bcd4, #18ffff)', tags: ['Data Flow', 'Visualization', 'ETL'], status: 'beta', statusLabel: 'BETA', date: '2026-07-07', author: 'T. Zieliński', version: '3.2.0', url: '/ai-reports/data-flow.html', metric: { label: 'Węzłów w grafie', value: 47, unit: '', display: 47, color: '#00bcd4' }, findings: ['3 źródła → 5 landingi → 8 BUFF → 12 DM → 24 raporty', 'Największy przepływ: Core Banking (12M rekordów/dzień)', '2 węzły z opóźnieniem >4h'], recommendations: ['Zoptymalizuj węzły z opóźnieniem', 'Dodaj monitoring przepływów krytycznych'] },
  { id: 'duplicate-logic', category: 'etl', title: 'Duplicate Logic Detector', desc: 'Znajduje powieloną logikę ETL — identyczne CASE, JOIN, Expression i funkcje w SQL i mappingach.', icon: '<svg width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><rect x="9" y="9" width="13" height="13" rx="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg>', accent: '#009688', gradient: 'linear-gradient(135deg, #009688, #4db6ac)', tags: ['ETL', 'Duplicate', 'Refactor', 'SQL'], status: 'new', statusLabel: 'NOWY', date: '2026-07-08', author: 'E. Mazur', version: '1.1.0', url: '/ai-reports/duplicate-logic.html', metric: { label: 'Duplikacje wykryte', value: 23, unit: '', display: 23, color: '#ff5252' }, findings: ['8 identycznych CASE WHEN w różnych mappingach', '5 powielonych JOIN między widokami', '7 duplikatów Expression w sesjach', '3 identyczne funkcje PL/SQL w pakietach'], recommendations: ['Wydziel CASE do osobnego widoku', 'Stwórz funkcję dla powielonych JOIN', 'Zrefaktoryzuj Expression do shared objects'] },
  { id: 'data-mapping', category: 'etl', title: 'Data Mapping Prototype', desc: 'Prototyp mapowania danych między systemem źródłowym (Core Banking) a DWH.', icon: '<svg width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"/></svg>', accent: '#ff9100', gradient: 'linear-gradient(135deg, #ff9100, #ffc400)', tags: ['Mapping', 'ETL', 'DWH'], status: 'stable', statusLabel: 'STABILNY', date: '2026-07-04', author: 'R. Krawczyk', version: '2.1.4', url: '/ai-reports/data-mapping.html', metric: { label: 'Pokrycie mapowania', value: 84, unit: '%', display: 84, color: '#ff9100' }, findings: ['15 pól źródłowych bez mapowania', '3 transformacje o niepotwierdzonej logice', 'Luki w mapowaniu wymiarów'], recommendations: ['Uzupełnij brakujące mapowania', 'Zweryfikuj logikę transformacji'] },
  { id: 'deployment-risk', category: 'risk', title: 'Deployment Risk Analyzer', desc: 'Ocena ryzyka wdrożenia na podstawie Deployment Group, XML, Jira i Git.', icon: '<svg width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"/></svg>', accent: '#ff5252', gradient: 'linear-gradient(135deg, #ff5252, #ff8a80)', tags: ['Deployment', 'Risk', 'Jira', 'Git'], status: 'new', statusLabel: 'NOWY', date: '2026-07-08', author: 'A. Wójcik', version: '1.2.0', url: '/ai-reports/deployment-risk.html', metric: { label: 'Risk Score', value: 68, unit: '/100', display: 68, color: '#ff5252' }, findings: ['Wpływ na 12 procesów downstream', 'Zmiana dotyczy 8 krytycznych tabel', 'Wymagany restart schedulerów', 'Brak testów regresyjnych dla 3 mappingów'], recommendations: ['Wykonaj pełny regression test', 'Zaplanuj okno wdrożeniowe poza godzinami batch', 'Przygotuj rollback script'] },
  { id: 'oracle-impact', category: 'risk', title: 'Oracle Object Impact Analyzer', desc: 'Analiza wpływu zmian na tabelach, widokach i procedurach.', icon: '<svg width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><circle cx="12" cy="12" r="10"/><circle cx="12" cy="12" r="6"/><circle cx="12" cy="12" r="2"/></svg>', accent: '#ff1744', gradient: 'linear-gradient(135deg, #ff1744, #d50000)', tags: ['Oracle', 'Impact', 'Objects', 'Dependencies'], status: 'beta', statusLabel: 'BETA', date: '2026-07-07', author: 'B. Szymański', version: '3.0.1', url: '/ai-reports/oracle-impact.html', metric: { label: 'Impact Score', value: 81, unit: '/100', display: 81, color: '#ff1744' }, findings: ['34 zależne widoki od tabeli FCT_SALES', '12 procedur wymagających rekompilacji', '7 mappingów ETL korzystających z obiektu', '4 raporty BI oparte na zmienianym widoku'], recommendations: ['Przeanalizuj każdą ścieżkę zależności', 'Zaplanuj zmianę poza godzinami szczytu', 'Powiadom właścicieli raportów BI'] },
  { id: 'data-quality', category: 'risk', title: 'Data Quality Analyzer', desc: 'Kompleksowa analiza jakości danych: NULL, duplikaty, spójność FK/PK.', icon: '<svg width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg>', accent: '#ffab00', gradient: 'linear-gradient(135deg, #ffab00, #ffd740)', tags: ['Data Quality', 'Validation', 'DQ'], status: 'new', statusLabel: 'NOWY', date: '2026-07-08', author: 'Ł. Dąbrowski', version: '2.0.0', url: '/ai-reports/data-quality.html', metric: { label: 'Quality Score', value: 76, unit: '/100', display: 76, color: '#ffab00' }, findings: ['12.4% NULL w kluczowych kolumnach', '2 345 duplikatów PK w tabeli CUSTOMER_DIM', 'Niespójność dat między warstwą DM a Raportami', '8 wartości odstających w kolumnach finansowych'], recommendations: ['Uruchom proces czyszczenia duplikatów', 'Dodaj constrainty NOT NULL', 'Zweryfikuj zakresy dat w procesach ETL'] },
  { id: 'test-generator', category: 'risk', title: 'Auto Test Generator', desc: 'Automatycznie wygenerowane testy na podstawie analizy SQL.', icon: '<svg width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/></svg>', accent: '#d500f9', gradient: 'linear-gradient(135deg, #d500f9, #e040fb)', tags: ['Testy', 'SQL', 'Automatyzacja'], status: 'stable', statusLabel: 'STABILNY', date: '2026-07-04', author: 'D. Woźniak', version: '1.3.2', url: '/ai-reports/test-generator.html', metric: { label: 'Pokrycie testami', value: 67, unit: '%', display: 67, color: '#d500f9' }, findings: ['45 testów wygenerowanych', '12 brakujących referencji wykrytych', '8 duplikacji w logice ETL'], recommendations: ['Rozszerz testy o przypadki brzegowe', 'Automatyzuj walidację po deploymentach'] },
  { id: 'doc-generator', category: 'docs', title: 'Documentation Generator', desc: 'Automatyczne generowanie dokumentacji technicznej procesów ETL.', icon: '<svg width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/></svg>', accent: '#448aff', gradient: 'linear-gradient(135deg, #448aff, #82b1ff)', tags: ['Documentation', 'ETL', 'Markdown', 'PDF'], status: 'new', statusLabel: 'NOWY', date: '2026-07-08', author: 'K. Kozłowski', version: '2.1.0', url: '/ai-reports/doc-generator.html', metric: { label: 'Dokumentacja', value: 100, unit: '%', display: '✓ Gotowe', color: '#448aff' }, findings: ['5 procesów udokumentowanych', '3 diagramy przepływu wygenerowane', 'Dokumentacja w 3 formatach: MD, HTML, PDF'], recommendations: ['Dodaj sekcję SLA dla każdego procesu', 'Zintegruj z Confluence API'] },
  { id: 'release-summary', category: 'docs', title: 'Release Summary Generator', desc: 'Raport wydania na podstawie Deployment Group: Jira, Git, SQL, XML.', icon: '<svg width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><polyline points="22 12 18 12 15 21 9 3 6 12 2 12"/></svg>', accent: '#2979ff', gradient: 'linear-gradient(135deg, #2979ff, #448aff)', tags: ['Release', 'Jira', 'Git', 'Deployment'], status: 'beta', statusLabel: 'BETA', date: '2026-07-07', author: 'M. Jankowski', version: '3.0.0', url: '/ai-reports/release-summary.html', metric: { label: 'Przygotowanie', value: 85, unit: '%', display: 85, color: '#2979ff' }, findings: ['Release R-2026.07: 12 zmian, 8 Jira ticketów', '3 nowe tabele, 2 usunięte obiekty', '4 workflow zmodyfikowane', 'Wymagany restart schedulerów'], recommendations: ['Wykonaj such-run przed deploymentem', 'Przygotuj raport po-wdrożeniowy', 'Zaktualizuj runbook'] },
  { id: 'scheduler-optimization', category: 'docs', title: 'Scheduler Optimization Report', desc: 'Analiza harmonogramów AutomateNow: wykrywanie kolizji, wąskich gardeł.', icon: '<svg width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>', accent: '#00e5ff', gradient: 'linear-gradient(135deg, #00e5ff, #18ffff)', tags: ['Scheduler', 'AutomateNow', 'Optimization'], status: 'new', statusLabel: 'NOWY', date: '2026-07-08', author: 'A. Kwiatkowska', version: '1.0.4', url: '/ai-reports/scheduler-optimization.html', metric: { label: 'Optymalizacja', value: 40, unit: '% oszczędności', display: 40, color: '#00e5ff' }, findings: ['5 kolizji okien batchowych', '3 joby z czasem wykonania >6h', 'Niewykorzystana równoległość w oknie nocnym', 'Wąskie gardło: proces ładowania DM'], recommendations: ['Przesuń joby poza kolizje', 'Zwiększ równoległość w oknie 00-04', 'Podziel najdłuższe joby na mniejsze partie'] },
]

const categories = {
  all: { id: 'all', label: 'Wszystkie', icon: '<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/></svg>' },
  sql: { id: 'sql', label: 'SQL & Optymalizacja', icon: '<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="16 18 22 12 16 6"/><polyline points="8 6 2 12 8 18"/></svg>' },
  etl: { id: 'etl', label: 'ETL & Zależności', icon: '<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polygon points="12 2 22 8.5 22 15.5 12 22 2 15.5 2 8.5 12 2"/></svg>' },
  risk: { id: 'risk', label: 'Ryzyko & Jakość', icon: '<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"/></svg>' },
  docs: { id: 'docs', label: 'Dokumentacja & Release', icon: '<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/></svg>' },
}

const filterCategories = computed(() => Object.values(categories).map(c => ({ ...c, count: c.id === 'all' ? allReports.length : allReports.filter(r => r.category === c.id).length })))

const filteredReports = computed(() => activeCategory.value === 'all' ? allReports : allReports.filter(r => r.category === activeCategory.value))

const sortedReports = computed(() => {
  const list = filteredReports.value
  if (!activeReport.value) return list
  const activeIdx = list.findIndex(r => r.id === activeReport.value)
  if (activeIdx < 0 || activeIdx === 0) return list
  const rowStart = Math.floor(activeIdx / 3) * 3
  if (activeIdx === rowStart) return list
  const result = [...list]
  const [card] = result.splice(activeIdx, 1)
  result.splice(rowStart, 0, card)
  return result
})

function toggleReport(id) {
  activeReport.value = activeReport.value === id ? null : id
}
</script>

<style scoped>
.hub-view { width: 100%; max-width: var(--content-width, 1200px); }
.hub-section-header { margin-bottom: 12px; }
.section-title { font-size: 24px; font-weight: 700; color: var(--text-primary); margin: 0 0 8px 0; letter-spacing: -0.3px; }
.section-desc { font-size: 14px; line-height: 1.6; color: var(--text-secondary); margin: 0; max-width: 680px; }
.report-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px; grid-auto-flow: row dense; margin-bottom: 24px; }
</style>